// LeaseFields: {
            //     formId: "billing_form",
            //     FormCol: 24,
            //     FieldSpace: 24,
            //     justifyField: "center",
            //     FormLayout: "inline",
            //     layout: { labelCol: { span: 9 }, wrapperCol: { span: 0 } },
            //     size: "middle",
            //     fields: [
            //         {
            //             Placeholder: "Leasing Company Name",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             Placeholder: "Lease Start Date",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "lease",
            //             fieldCol: 12,
            //             key: "payslipEmail",
            //             size: "small",
            //             type: "input",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Payment Email is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             object: "lease",
            //             fieldCol: 12,
            //             key: "leaseStart",
            //             size: "small",
            //             type: "DatePicker",
            //             fieldStyle: { width: "100%" },
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Start Date is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             Placeholder: "Lease End Date",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             Placeholder: "MV Rego Number",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "lease",
            //             fieldCol: 12,
            //             key: "leaseEnd",
            //             size: "small",
            //             type: "DatePicker",
            //             fieldStyle: { width: "100%" },
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Start Date is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "mvNumber",
            //             size: "small",
            //             type: "input",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Payment Email is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             Placeholder: "MV Make & Model",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             Placeholder: "Financer",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "mvModel",
            //             size: "small",
            //             type: "input",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Payment Email is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },{
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "financer",
            //             size: "small",
            //             type: "input",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Payment Email is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },

            //         {
            //             Placeholder: "Payslip Email",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "type",
            //             size: "small",
            //             data: [
            //                 { label: "Casual", value: 1 },
            //                 { label: "Part Time", value: 2 },
            //                 { label: "Full Time", value: 3 },
            //             ],
            //             type: "Select",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Account Number",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "payslipEmail",
            //             size: "small",
            //             type: "input",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Payment Email is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             Placeholder: "Full Work Week Hours",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
                    
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "noOfHours",
            //             size: "small",
            //             type: "InputNumber",
            //             // shape: " Hours",
            //             fieldStyle: { width: "100%" },
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "How much he Cost",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
                    
                    
            //         {
            //             Placeholder: "Annual Base Salary",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "endDate",
            //             size: "small",
            //             type: "DatePicker",
            //             fieldStyle: { width: "100%" },
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Start Date is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "remunerationAmount",
            //             size: "small",
            //             type: "InputNumber",
            //             shape: "$",
            //             fieldStyle: { width: "100%" },
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "How much he Cost",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },  
            //         {
            //             Placeholder: "Hourly Rate",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             Placeholder: "Pay Frequence",
            //             fieldCol: 12,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "hourlyrate",
            //             size: "small",
            //             type: "InputNumber",
            //             shape: "$",
            //             fieldStyle: { width: "100%" },
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "How much he Cost",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         }, 
            //         {
            //             object: "billing",
            //             fieldCol: 12,
            //             key: "payFrequency",
            //             size: "small",
            //             data: [
            //                 { label: "Hourly", value: 1 },
            //                 { label: "Daily", value: 2 },
            //                 { label: "Weekly", value: 3 },
            //                 { label: "Fortnightly", value: 4 },
            //                 { label: "Monthly", value: 5 },
            //             ],
            //             type: "Select",
            //             // rules: [
            //             //     {
            //             //         required: true,
            //             //         message: "Payment Frequncy is required",
            //             //     },
            //             // ],
            //             itemStyle: { marginBottom: 1 },
            //         },
            //         {
            //             Placeholder: "Comments",
            //             fieldCol: 24,
            //             size: "small",
            //             type: "Text",
            //             labelAlign: "right",
            //             // itemStyle:{marginBottom:'10px'},
            //         },
            //         {
            //             object: "billing",
            //             fieldCol: 24,
            //             key: "payslipEmail",
            //             size: "small",
            //             type: "Textarea",
            //             itemStyle: { marginBottom: 1 },
            //         },
            //     ],
            // },