fields={
    backstyle: 'style on the Row',
    Formstyle:' style on the Form ',
    FormCol: 'form Column',
    FieldSpace: 'Spaces between fields i.e={ xs: 12, sm: 16, md: 122}',
    layout: 'set label column for alignment',
    FormLayout: 'ant desingn has 3 layout // horizonta, vertical, inline',
    justify: 'form',
    initialValues:{obj:{key:'value'}},
    fields:[ 
        { //fileds
            object: 'Object in what value to get objec',
            fieldCol: 'how manu column should get',
            key: 'key of the object to get',
            Placeholder: 'placeholder to show in the input fields && span to put things also i.e <Icons/>',
            label: 'Label of the fields ',
            rules:[{types:'types of rules', message:'to show on rule'}],
            type: `Input, Password, Textarea, InputNumber, Select, Switch, Radio, 
                    DatePicker, TimePicker, TimeRange,RangePicker CheckboxGroup Checkbox 
                    Title Span Divider Button `,
            layout:  {
                labelCol: { span: 'number for the label column by the froms' },
                wrapperCol: { span: 'number for the column by Froms ' } 
            },
            size: 'size of the input fields',
            mode: 'changes according to the input option i.e type (where type is needed), level(in Title), autosize(in text field), visibilityToggle(in password) ',
            labelAlign: 'label  align in the column of Form ',
            hint: 'hint',
            data: 'Option for the fields that needs i.e checkbox selectbox',
            itemStyle: 'put style on from item for the field',
            fieldStyle = 'put style directly to the field ',
            valuePropName:'"checked" for the field name as checkbox and switch and fileList for Dragger',
            func : ' (value, e) function on the field onChange or click',
            rangMin: 'To set min number to a input field',
            rangMax: 'To set max number to a input field and if multiple allowed',
            // default: 'might work n something... form initial value is working at the time',
            showTime: 'boolean for datePicker to show Time as well and string for TimePicker for format...',
            shape: 'to set shape for Button and buttonStle for Radio prop and suffix in input fields',
            size: 'set Size of any element',
            func: 'onChange function on anyFiled',
            fieldStyle: 'style on the field',
            getValue: 'If field is not getting getValueFromEvent',
            noStyle: "If don't want form style"
        } 
    ]
}

const Example = {
    // Title: 'OneLM CRM',
    justify : 'center',
    FormCol: 10,
    FieldSpace: { xs: 12, sm: 16, md: 122},
    layout: {labelCol: { span: 12 }},
    justifyField:'center',
    FormLayout:'vertical', 
    size: 'middle',
    Formstyle:{backgroundColor:'white'},
    backstyle:{backgroundColor:'green'},
    fields:[
        {
            object:'obj',
            fieldCol:13,
            variable: 'name',
            Placeholder: 'Your Good Name',
            label:'Name',
            // rules:[{ required: true }],
            type: 'input',
            layout: {labelCol: { span: 0}},
            labelAlign: 'right',
            hint: 'write your Name',
        },
        {
            object:'obj',
            fieldCol:13,
            variable: 'password',
            label:'Password',
            Placeholder: "You Don't Have Any",
            // rules:[{ required: true, message: 'Please input your password!' }],
            type: 'password',
            layout: {labelCol: { span: 0 }},
            labelAlign: 'right',
            hint: 'Nick Name',
        },
        {
            object:'obj',
            Placeholder: "You Don't Have Any",
            fieldCol:12,
            variable: 'age',
            label:'Age',
            // rules:[{ type: 'number', min: 0, max: 99 }],
            rangMin: 1,
            rangMax:2,
            type: 'inputNumber',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'whats your Age'
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'age',
            label:'Age',
            // rules:[{ required: true }],
            type: 'input',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'Age in Time',
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'age',
            label:'Age',
            // rules:[{ required: true }],
            type: 'input',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'Age in Time',
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'select1',
            label:'Select Me',
            // rules:[{ required: true }],
            type: 'select',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'You can select',
            mode: 'multiple',
            data:[
                {label:'sameer',value:0},
                {label:'Adii',value:1},
                {label:'caio',value:2}
            ]
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'select2',
            label:'Select Me',
            // rules:[{ required: true }],
            type: 'select',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'You can select',
            mode: 'tag',
            data:[
                {label:'Mursal',value:0},
                {label:'Asad',value:1},
                {label:'Shohail',value:2}
            ]
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'switch',
            label:'Switch',
            // rules:[{ required: true,  message: 'do it' }],
            type: 'switch',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'pick me',
            valuePropName:'checked' // passing an error if not 
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'radio',
            label:'Radio-Group',
            // rules:[{ required: true }],
            type: 'radio',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'right',
            hint: 'FM Radio',
            data:[
                {label:'Mursal',value:0,disabled:true},
                {label:'Asad',value:1},
                {label:'Shohail',value:2}
            ],
            default:2,
            mode: 'button'
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'date',
            label:'Date',
            // rules:[{ required: true }],
            type: 'DatePicker',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'left',
            hint: 'Whats your Date???',
            mode:'date',
        },
        {
            object:'obj',
            fieldCol:10,
            variable: 'range',
            label:'Range Date',
            // rules:[{ required: true }],
            type: 'RangePicker',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'left',
            hint: 'Whats your Range???',
            mode:'date',
        },
        {
            object:'obj2',
            fieldCol:10,
            variable: 'check',
            label:'Checking',
            // rules:[{ required: true }],
            type: 'CheckboxGroup',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'left',
            data:[
                {label:'Mursal',value:0,disabled:true},
                {label:'Asad',value:1},
                {label:'Shohail',value:2}
            ],
            hint: 'choose us...',
            valuePropName:'checked' // passing an error if not 
        },
        {
            object:'obj4',
            fieldCol:10,
            variable: 'checkBox',
            label:'Checking',
            // rules:[{ required: true }],
            type: 'Checkbox',
            layout: {labelCol: { span: 8 }},
            labelAlign: 'left',
            hint: 'choose us...', 
            valuePropName:'checked' // passing an error if not 
        },
        { //lables
            object:'obj',
            fieldCol:20,
            layout:  {
                wrapperCol: { span: 0 }
            },
            Placeholder: 'OLCRM usernmae',
            mode:5,
            type: 'Title',
        },
    ]
}